
platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

workspace 'MyPublicEdu'

target 'MyPublicEdu' do

pod 'MMDrawerController', '~> 0.6.0'
pod 'MJRefresh', '~> 3.1.15.3'
pod 'SnapKit', '~> 4.0.0'
pod 'RESideMenu'
pod 'Alamofire', '~> 4.7.0'
pod "SwiftyJSON"

end

